# Generated by Django 3.0 on 2023-03-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
